library(dtw)

dtwDistanceMatrix <- function(x, y)
# Computes a euclidean distance matrix for two given densities.
#
# Args:
#   x: First density of length n.
#   y: Second density of length m.
#
# Returns:
#   A n-by-m matrix with pairwise euclidean distances.
{
    dist(x, y)
}

derivativeDtwDistanceMatrix <- function(x, y)
# Computes a distance matrix for derivative DTW, given two densities.
#
# Args:
#   x: First density of length n.
#   y: Second density of length n.
#
# Returns:
#   A n-by-n matrix with pairwise derivative distances.    
{
    if(length(x) != length(y))
    {
        stop('Densities x and y must be of same length.')
    }

    difX <- sapply(2:(length(x)-1), function(i) (x[i] - x[i-1]) + ((x[i+1] - x[i-1]) / 2) / 2)
    difX <- c(difX[1], difX, difX[length(x)-2])
    difY <- sapply(2:(length(x)-1), function(i) (y[i] - y[i-1]) + ((y[i+1] - y[i-1]) / 2) / 2)
    difY <- c(difY[1], difY, difY[length(x)-2])                
    dist(difX, difY)
}

weighDtwDistances <- function(m, g = 0.025)
# Given a DTW distance matrix, weighs it according to Weighted DTW.
#
# Args:
#   m: Distance matrix, i.e. as generated by dtwDistanceMatrix() or derivativeDtwDistanceMatrix().
#   g: Steepness of the underlying sigmoid function.
#
# Returns:
#   A matrix of the same size of the input matrix, containing weighted elements.
{    
    n <- nrow(m)
    w <- 1 / (1 + exp(-g * (as.matrix(dist(1:n)) - n / 2)))
    w * m
}

myDtw <- function(a, b, ...)
# There is a global proxy function which modularizes the parameters for DTW to
# ensure consistent use throughout flowLearn. To Change DTW parameters, change
# this function.
# Calls dtw::dtw with parameters suitable for flowLean.
#
# Args:
#   a: First density of length n.
#   b: Second density of length n.
#
# Returns:
#   An dtw object as returned by dtw::dtw.
{
    # dtw(a, b, ...)

    ddtw <- dtw(derivativeDtwDistanceMatrix(a, b), step.pattern = typeIds, ...)

    # When using derivative DTW, we set the original densities as query and
    # reference for easier visualization
    ddtw$query <- a
    ddtw$reference <- b
    ddtw
}
